mappings:
- source_url: https://yitang.top/fs-doc/c625f36d3f91712f021d5bfbc47e7ae1/SCaodfwWnomwojxHxKocInkun1x
  target_url: https://arqiaoknow.feishu.cn/wiki/F0DewQbmniETxPkhOaYcKaVSnXe
local_export_dir: localscript
content_range:
  start_heading: 开始上课
  end_heading: 作业与Candy
full_copy_titles:
- AI落地Live
